Kobold:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Hobgoblin:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Ent:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Mummy:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Ghoul:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Ogre:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Cyclops:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Manticore:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Elemental:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Giant Spider:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Ice Elemental:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Fire Elemental:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0
Demon Lord:
    damage: 1.0
    health: 1.0
    movement speed: 1.0
    health per star: 0.15
    damage per star: 0.125
    attack speed per star: 0.1
    damage taken: 1.0